---
 - name: test
   command: echo lets start the test
 - name: /etc/host template
   #template: src=roles/base/templates/etc_hosts.j2 dest=/etc/hosts owner=root group=root mode=0640
   template: src=etc_hosts.j2 dest=/etc/hosts owner=root group=root mode=0640
